version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - INSTANCE=production
      - MYSQL_HOST=
      - MYSQL_PORT=3306
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
      - HOST=
    command: npm start

